fullnameOverride: monitoring

alertmanager:
  enabled: false

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  image:
    registry: crpi-guf725ppv0myjkdj.cn-hangzhou.personal.cr.aliyuncs.com
    repository: online-bookstore/bookstore-backend
    tag: grafana-13.0.1-security-01
  sidecar:
    image:
      registry: quay.io
      repository: kiwigrid/k8s-sidecar
      tag: 2.7.3
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

prometheus:
  prometheusSpec:
    image:
      registry: quay.io
      repository: prometheus/prometheus
      tag: v3.11.3-distroless
    retention: 24h
    retentionSize: 512MB
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    storageSpec: {}

prometheusOperator:
  admissionWebhooks:
    enabled: false
    tls:
      enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

kube-state-metrics:
  image:
    registry: crpi-guf725ppv0myjkdj.cn-hangzhou.personal.cr.aliyuncs.com
    repository: online-bookstore/bookstore-backend
    tag: kube-state-metrics-v2.19.0
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 96Mi

prometheus-node-exporter:
  image:
    registry: quay.io
    repository: prometheus/node-exporter
    tag: v1.11.1-distroless
    distroless: true
  resources:
    requests:
      cpu: 20m
      memory: 24Mi
    limits:
      cpu: 100m
      memory: 64Mi

kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
