fullnameOverride: monitoring

alertmanager:
  enabled: false

grafana:
  enabled: true
  defaultDashboardsEnabled: true
  deploymentStrategy:
    type: Recreate
    rollingUpdate: null
  persistence:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi
prometheus:
  prometheusSpec:
    retention: 24h
    retentionSize: 512MB
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 512Mi
    storageSpec: {}

prometheusOperator:
  admissionWebhooks:
    enabled: false
  tls:
    enabled: false
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi

kube-state-metrics:
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 96Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 20m
      memory: 24Mi
    limits:
      cpu: 100m
      memory: 64Mi

kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
