apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bookstore
spec:
  ingressClassName: traefik
  rules:
    - host: bookstore.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: bookstore-backend
                port:
                  number: 8000
          - path: /health
            pathType: Exact
            backend:
              service:
                name: bookstore-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bookstore-frontend
                port:
                  number: 80
