apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bookstore-production
resources:
  - ../../base
  - namespace.yaml
replicas:
  - name: bookstore-backend
    count: 2
  - name: bookstore-frontend
    count: 2
patches:
  - target:
      kind: Ingress
      name: bookstore
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: bookstore.example.com
