name: Online Book Store CI

on:

  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:

  backend-test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -r app/backend/requirements.txt

      - name: Run unit tests
        run: |
          pytest tests/unit
